# Generated by Django 3.2.4 on 2021-06-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('apelido', models.CharField(default='', max_length=35)),
                ('email', models.CharField(max_length=50)),
                ('idade', models.IntegerField(default=1)),
                ('data_nascimento', models.DateField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao1', models.CharField(max_length=100)),
                ('questao2', models.CharField(max_length=100)),
                ('questao3', models.CharField(max_length=100)),
                ('questao4', models.CharField(max_length=100)),
                ('questao5', models.CharField(max_length=100)),
                ('questao6', models.CharField(max_length=100)),
                ('questao7', models.CharField(max_length=100)),
                ('questao8', models.CharField(max_length=100)),
                ('questao9', models.CharField(max_length=100)),
                ('questao10', models.CharField(max_length=100)),
            ],
        ),
    ]
